// DOM Elements //

const cover = document.getElementById('cover')
const musicName = document.getElementById('music-name')
const singer = document.getElementById('singer')
const like = document.getElementById('like')
const dislike = document.getElementById('dislike')
const currentTime = document.getElementById('current-time')
const duration = document.getElementById('duration')
const playlist = document.getElementById('playlist')
const back = document.getElementById('back')
const playPause = document.getElementById('play')
const pause = document.getElementById('pause')
const next = document.getElementById('next')
const repeat = document.getElementById('repeat')
const repeatOne = document.getElementById('repeat-one')
const shuffle = document.getElementById('shuffle')
